version: '2'
# use a shared volume
# docker create volume 
volumes: 
  ri:
    name: redisinsight
    external: true
services:
  redis:
    # apt-get install -y procps
    image: redislabs/redismod:latest
    volumes:
      - ./data:/data
    ports: 
      - "6379:6379"
  war:
    build: .
    image: redis-session-war
    links:
      - redis:redis
    ports:
      - "8080:8080"
  ri:
    image: redislabs/redisinsight
    volumes:
      - ri:/db
    ports:
      - "8001:8001"
    links:
      - redis:redis